services:
  - type: web
    name: eda-music-frontend-static
    env: static
    autoDeploy: true
    staticPublishPath: static
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
