"""
Signal 1 — Catalog Coherence (Exercise 1)
==========================================
Ghost artists tend to have unnaturally uniform catalogs:
every track sounds statistically identical because they are
generated by the same AI loop with fixed parameters.

Method:
- Fetch all track IDs for an artist via Spotify API
- Join with Kaggle audio features dataset (bypasses blocked endpoint)
- Compute per-artist variance in 4D feature space (danceability, energy, valence, acousticness)
- Run PCA on the catalog and compare explained-variance ratio
- Score: LOW overall_variance → suspicious (ghost-like)

Thresholds (calibrated on seed set):
- overall_variance < 0.02  → HIGH suspicion
- 0.02 – 0.06             → MEDIUM
- > 0.06                  → LOW (organic-like)
"""
from __future__ import annotations

import numpy as np
import pandas as pd
from loguru import logger
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

from src.api.spotify_client import SpotifyClient
from src.utils.kaggle_loader import kaggle, FEATURE_4D, AUDIO_FEATURES

# Suspicion thresholds — tuned on organic seed calibration
HIGH_SUSPICION_THRESHOLD = 0.02
MEDIUM_SUSPICION_THRESHOLD = 0.06


def score_artist(
    artist_id: str,
    spotify: SpotifyClient,
    *,
    use_full_catalog: bool = False,
) -> dict:
    """
    Compute catalog coherence score for one artist.

    Parameters
    ----------
    artist_id       Spotify artist ID
    spotify         SpotifyClient instance
    use_full_catalog  If True, fetches full catalog with ISRC (slow).
                      If False, fetches album list and uses album track IDs (faster).

    Returns
    -------
    dict with keys:
        artist_id, artist_name, track_count, kaggle_hit_rate,
        variance_per_feature (dict), overall_variance,
        pca_explained_variance (list), pca_top_component (list),
        suspicion_level ("HIGH"/"MEDIUM"/"LOW"), suspicion_score (0.0–1.0)
    """
    # --- 1. Get track IDs ---
    if use_full_catalog:
        tracks = spotify.get_artist_full_catalog(artist_id)
        track_ids = [t["id"] for t in tracks]
        track_names = {t["id"]: t["name"] for t in tracks}
    else:
        # Faster path: album → track IDs without ISRC fetching
        albums = spotify.get_artist_albums(artist_id, include_groups="album,single")
        track_ids = []
        track_names = {}
        for album in albums:
            for t in spotify.get_album_tracks(album["id"]):
                track_ids.append(t["id"])
                track_names[t["id"]] = t["name"]

    artist_meta = spotify.get_artist(artist_id)
    artist_name = artist_meta.get("name", artist_id)

    if not track_ids:
        logger.warning(f"No tracks found for {artist_name} ({artist_id})")
        return _empty_result(artist_id, artist_name)

    logger.info(f"Scoring catalog coherence for {artist_name}: {len(track_ids)} tracks")

    # --- 2. Join with Kaggle audio features ---
    feat_df = kaggle.get_features(track_ids)
    available_feats = [f for f in FEATURE_4D if f in feat_df.columns]

    hit_count = int(feat_df[available_feats[0]].notna().sum()) if available_feats else 0
    kaggle_hit_rate = hit_count / len(track_ids) if track_ids else 0.0

    if not available_feats or hit_count < 3:
        logger.warning(
            f"{artist_name}: only {hit_count}/{len(track_ids)} tracks in Kaggle dataset "
            f"(need ≥3 for variance). Returning partial result."
        )
        return {
            **_empty_result(artist_id, artist_name),
            "track_count": len(track_ids),
            "kaggle_hit_rate": kaggle_hit_rate,
        }

    # --- 3. Variance in 4D feature space ---
    valid = feat_df[available_feats].dropna()
    variances = {f: float(valid[f].var()) for f in available_feats}

    cov = np.cov(valid[available_feats].values.T)
    if cov.ndim == 0:
        overall_variance = float(cov)
    else:
        overall_variance = float(np.mean(np.linalg.eigvalsh(cov)))

    # --- 4. PCA ---
    if len(valid) >= 2 and len(available_feats) >= 2:
        scaler = StandardScaler()
        scaled = scaler.fit_transform(valid[available_feats])
        n_components = min(len(available_feats), len(valid))
        pca = PCA(n_components=n_components)
        pca.fit(scaled)
        explained = pca.explained_variance_ratio_.tolist()
        top_component = pca.components_[0].tolist()
    else:
        explained = []
        top_component = []

    # --- 5. Suspicion score ---
    # Map overall_variance to [0, 1] where 1 = most suspicious
    # Organic artists typically: overall_variance ≈ 0.03–0.15
    # Ghost artists typically:   overall_variance ≈ 0.001–0.015
    suspicion_score = _variance_to_suspicion(overall_variance)
    if suspicion_score >= 0.7:
        suspicion_level = "HIGH"
    elif suspicion_score >= 0.4:
        suspicion_level = "MEDIUM"
    else:
        suspicion_level = "LOW"

    logger.info(
        f"{artist_name}: overall_variance={overall_variance:.4f}, "
        f"suspicion={suspicion_level} ({suspicion_score:.2f}), "
        f"kaggle_hit_rate={kaggle_hit_rate:.1%}"
    )

    return {
        "artist_id": artist_id,
        "artist_name": artist_name,
        "track_count": len(track_ids),
        "kaggle_hit_count": hit_count,
        "kaggle_hit_rate": kaggle_hit_rate,
        "variance_per_feature": variances,
        "overall_variance": overall_variance,
        "pca_explained_variance": explained,
        "pca_top_component": top_component,
        "pca_features": available_feats,
        "suspicion_level": suspicion_level,
        "suspicion_score": suspicion_score,
    }


def score_seed_set(spotify: SpotifyClient, seeds: list[dict]) -> pd.DataFrame:
    """
    Score all seed artists and return a comparison DataFrame.

    Parameters
    ----------
    seeds   list of dicts from ground_truth.get_all_seeds()
            Each must have: spotify_id, name, is_ghost

    Returns
    -------
    DataFrame with one row per artist, sorted by suspicion_score descending
    """
    rows = []
    for seed in seeds:
        sid = seed.get("spotify_id")
        if not sid:
            logger.warning(f"Skipping {seed['name']} — no spotify_id")
            continue
        result = score_artist(sid, spotify)
        result["is_ghost_label"] = seed.get("is_ghost", False)
        result["genre"] = seed.get("genre", "")
        rows.append(result)

    if not rows:
        return pd.DataFrame()

    df = pd.DataFrame(rows)
    df = df.sort_values("suspicion_score", ascending=False).reset_index(drop=True)
    return df


def _variance_to_suspicion(variance: float) -> float:
    """
    Map overall_variance to suspicion score [0, 1].
    Uses sigmoid-like mapping anchored at empirical thresholds.
    """
    if variance <= 0:
        return 1.0
    # log-scale: variance=0.005 → ~0.9, variance=0.06 → ~0.1
    import math
    log_v = math.log10(max(variance, 1e-6))
    # anchor: log10(0.02) ≈ -1.7 maps to 0.5
    score = 1.0 / (1.0 + math.exp(3.5 * (log_v + 1.7)))
    return float(np.clip(score, 0.0, 1.0))


def _empty_result(artist_id: str, artist_name: str) -> dict:
    return {
        "artist_id": artist_id,
        "artist_name": artist_name,
        "track_count": 0,
        "kaggle_hit_count": 0,
        "kaggle_hit_rate": 0.0,
        "variance_per_feature": {},
        "overall_variance": 0.0,
        "pca_explained_variance": [],
        "pca_top_component": [],
        "pca_features": [],
        "suspicion_level": "UNKNOWN",
        "suspicion_score": 0.0,
    }


def summary_table(df: pd.DataFrame) -> str:
    """Return a formatted text summary table for quick inspection."""
    if df.empty:
        return "No results."
    cols = ["artist_name", "is_ghost_label", "track_count", "kaggle_hit_rate",
            "overall_variance", "suspicion_level", "suspicion_score"]
    display = df[[c for c in cols if c in df.columns]].copy()
    display["kaggle_hit_rate"] = display["kaggle_hit_rate"].map("{:.0%}".format)
    display["overall_variance"] = display["overall_variance"].map("{:.4f}".format)
    display["suspicion_score"] = display["suspicion_score"].map("{:.2f}".format)
    return display.to_string(index=False)
