"""
scripts/14_false_positive_analysis.py

False Positive Analysis for the GhostTrack composite score.

Identifies organic artists scored above the ghost threshold at multiple
operating points. Categorizes false positives into 4 types:
  1. PROLIFIC_REAL      — legitimate artists with large catalogs (high S4)
  2. LIBRARY_COMPOSER   — stock music / sync composers (high volume, low variance)
  3. AGGREGATOR_USER    — single-registrant via DistroKid etc. (high HHI, organic)
  4. GENRE_SPECIALIST   — single-genre niche artists (high S5, organic)

Uses three threshold levels:
  - strict  (composite ≥ 0.983): nearly zero FP — only clearly ghost-like
  - moderate (composite ≥ 0.500): intermediate operating point
  - lenient (S2_proxy ≥ 0.800): broad screening (variance < 0.040)

Output:
  data/results/false_positives.csv
  writing/limitations.md (generated by this script)
"""

from __future__ import annotations

import logging
import sys
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler

logging.basicConfig(
    format="%(asctime)s | %(levelname)s | %(message)s",
    level=logging.INFO, stream=sys.stdout,
)
log = logging.getLogger(__name__)

ROOT    = Path(__file__).parent.parent
DATA    = ROOT / "data"
RESULTS = ROOT / "results" / "false_positives.csv"
WRITING = ROOT / "writing"
FIGURES = ROOT / "figures"
WRITING.mkdir(parents=True, exist_ok=True)

SIGNAL_NAMES = ["S2_bulk_proxy", "S4_catalog_density", "S5_genre_concentration"]

C_GHOST   = "#E74C3C"
C_ORGANIC = "#27AE60"
C_AMBER   = "#F39C12"
BG        = "#0a0a0a"

THRESHOLDS = {
    "strict":   0.983,
    "moderate": 0.500,
    "lenient":  None,   # S2 ≥ 0.800 (variance < 0.040)
}

# ── Known organic artist context ──────────────────────────────────────────────
# For artists appearing in top false positives, provide manual classification
# These are manually reviewed based on artist knowledge
ARTIST_CONTEXT: dict[str, dict] = {
    # Artists with single-genre focus (legitimate niche specialists)
    "The Black Dog":           {"type": "GENRE_SPECIALIST",  "note": "IDM/ambient electronic, Warp Records, highly consistent sound by design"},
    "Yasuharu Takanashi":      {"type": "LIBRARY_COMPOSER",  "note": "Anime composer; scores many series consistently"},
    "George Bruns":            {"type": "LIBRARY_COMPOSER",  "note": "Disney studio composer; uniform studio production"},
    "Ilkae":                   {"type": "GENRE_SPECIALIST",  "note": "Niche IDM artist; small catalog, consistent style"},
    "Death Cab for Cutie":     {"type": "PROLIFIC_REAL",     "note": "Verified indie band; high catalog size, consistent indie-pop"},
    "Two Steps from Hell":     {"type": "LIBRARY_COMPOSER",  "note": "Epic/trailer music composers; by design uniform high-energy"},
    "Audiomachine":            {"type": "LIBRARY_COMPOSER",  "note": "Film score/trailer music library; intentional sonic consistency"},
    "Really Slow Motion":      {"type": "LIBRARY_COMPOSER",  "note": "Epic cinematic music library"},
    "Position Music":          {"type": "LIBRARY_COMPOSER",  "note": "Licensed music production house"},
    "Epidemic Sound":          {"type": "LIBRARY_COMPOSER",  "note": "Stock music platform; low variance by design"},
    "Artlist":                 {"type": "LIBRARY_COMPOSER",  "note": "Licensed music platform, intentional uniformity"},
    "Sleeping At Last":        {"type": "GENRE_SPECIALIST",  "note": "Ambient/folk songwriter; consistent minimalist style"},
    "Ludovico Einaudi":        {"type": "GENRE_SPECIALIST",  "note": "Minimalist pianist; intentionally sparse variation"},
    "Max Richter":             {"type": "GENRE_SPECIALIST",  "note": "Neoclassical composer; consistent sound design"},
    "Johann Sebastian Bach":   {"type": "GENRE_SPECIALIST",  "note": "Classical; performed consistently across catalog"},
    "Johann Johannsson":       {"type": "GENRE_SPECIALIST",  "note": "Neoclassical film composer; consistent aesthetic"},
}


# ── FP category classifier ────────────────────────────────────────────────────

def categorize_fp(row: pd.Series) -> tuple[str, str]:
    """Rule-based false positive categorization."""
    artist = str(row["artist"])

    # Check manual context first
    for key, ctx in ARTIST_CONTEXT.items():
        if key.lower() in artist.lower():
            return ctx["type"], ctx["note"]

    # Rule-based heuristics
    s2 = float(row.get("S2_bulk_proxy", 0))
    s4 = float(row.get("S4_catalog_density", 0))
    s5 = float(row.get("S5_genre_concentration", 0))
    var = float(row.get("total_variance", 0.1))
    tc  = int(row.get("track_count", 0))

    if tc > 200:
        return "PROLIFIC_REAL", f"Large catalog ({tc} tracks) but organic; high S4={s4:.2f}"
    if var < 0.005 and s5 > 0.8:
        return "LIBRARY_COMPOSER", f"Very low variance ({var:.4f}), single genre; stock music pattern"
    if s5 > 0.9:
        return "GENRE_SPECIALIST", f"Single-genre specialist; S5={s5:.2f} but low S2={s2:.2f}"
    if s2 > 0.75 and tc < 50:
        return "AGGREGATOR_USER", f"Small but uniform catalog; possible single-release artist"

    return "OTHER_ORGANIC", f"Organic; S2={s2:.2f} S4={s4:.2f} S5={s5:.2f} var={var:.4f}"


# ── Main analysis ─────────────────────────────────────────────────────────────

def main() -> None:
    # Load data
    org = pd.read_csv(DATA / "processed" / "organic_controls_kaggle.csv")
    lv  = pd.read_csv(DATA / "processed" / "low_variance_artists.csv")
    org["label"] = 0
    lv["label"]  = 1

    cols = ["artist", "track_count", "total_variance", "genres", "genre_count", "label"]
    df = pd.concat([org[cols], lv[cols]], ignore_index=True)
    df["S2_bulk_proxy"]          = (1.0 - df["total_variance"] / 0.200).clip(0, 1)
    df["S4_catalog_density"]     = (df["track_count"] / 300.0).clip(0, 1)
    df["S5_genre_concentration"] = (1.0 / df["genre_count"].clip(1)).clip(0, 1)

    # Fit composite model
    X = df[SIGNAL_NAMES].values
    y = df["label"].values
    scaler = StandardScaler()
    X_s = scaler.fit_transform(X)
    lr = LogisticRegression(
        class_weight="balanced", C=1.0, max_iter=1000,
        random_state=42, solver="lbfgs",
    )
    lr.fit(X_s, y)
    df["composite_score"] = lr.predict_proba(X_s)[:, 1]

    organics = df[df["label"] == 0].copy()

    # ── Collect FPs at each threshold ────────────────────────────────────────
    fp_rows = []

    # Strict threshold (composite ≥ 0.983)
    strict_fp = organics[organics["composite_score"] >= THRESHOLDS["strict"]]
    for _, row in strict_fp.iterrows():
        cat, note = categorize_fp(row)
        fp_rows.append({**row.to_dict(), "threshold_regime": "strict", "fp_category": cat, "review_notes": note})

    # Moderate threshold (composite ≥ 0.500)
    mod_fp = organics[
        (organics["composite_score"] >= THRESHOLDS["moderate"]) &
        (organics["composite_score"] < THRESHOLDS["strict"])
    ]
    for _, row in mod_fp.iterrows():
        cat, note = categorize_fp(row)
        fp_rows.append({**row.to_dict(), "threshold_regime": "moderate", "fp_category": cat, "review_notes": note})

    # Lenient: S2 ≥ 0.800 (variance < 0.040), not already a ghost-proxy
    lenient_fp = organics[
        (organics["S2_bulk_proxy"] >= 0.800) &
        (organics["composite_score"] < THRESHOLDS["moderate"])
    ]
    for _, row in lenient_fp.iterrows():
        cat, note = categorize_fp(row)
        fp_rows.append({**row.to_dict(), "threshold_regime": "lenient", "fp_category": cat, "review_notes": note})

    fp_df = pd.DataFrame(fp_rows)

    print("\n" + "=" * 70)
    print("FALSE POSITIVE ANALYSIS")
    print("=" * 70)
    print(f"\nOrganic artists total: {len(organics)}")
    print(f"  Strict FPs  (composite ≥ {THRESHOLDS['strict']}): {len(strict_fp)}")
    print(f"  Moderate FPs (composite ≥ {THRESHOLDS['moderate']}): {len(mod_fp)}")
    print(f"  Lenient FPs  (S2 ≥ 0.800): {len(lenient_fp)}")

    if len(fp_df) > 0:
        print("\nFP Category Distribution:")
        print(fp_df["fp_category"].value_counts().to_string())

        print("\nStrict-threshold FPs (highest risk of real artist misclassification):")
        if len(strict_fp) == 0:
            print("  None — strict threshold has zero false positives on proxy dataset")
        else:
            print(strict_fp[["artist","total_variance","S2_bulk_proxy","composite_score"]]
                  .sort_values("composite_score", ascending=False).head(10).to_string(index=False))

        print("\nModerate-threshold FPs by category:")
        if len(fp_df[fp_df["threshold_regime"] == "moderate"]) > 0:
            for cat, grp in fp_df[fp_df["threshold_regime"] == "moderate"].groupby("fp_category"):
                print(f"\n  {cat} (n={len(grp)}):")
                for _, r in grp.head(5).iterrows():
                    print(f"    {r['artist'][:40]:40s}  var={r['total_variance']:.4f}  score={r['composite_score']:.3f}")
        else:
            print("  None")

        print("\nTop 20 lenient-threshold FPs (high S2, lower composite):")
        top_lenient = fp_df[fp_df["threshold_regime"] == "lenient"].nlargest(20, "S2_bulk_proxy")
        if len(top_lenient) > 0:
            print(top_lenient[["artist","total_variance","S2_bulk_proxy","fp_category","review_notes"]]
                  .head(20).to_string(index=False))

    # Save FP CSV
    if len(fp_df) > 0:
        fp_out_cols = ["artist","label","total_variance","genres","track_count",
                       "S2_bulk_proxy","S4_catalog_density","S5_genre_concentration",
                       "composite_score","threshold_regime","fp_category","review_notes"]
        fp_df[fp_out_cols].to_csv(RESULTS, index=False)
        log.info("Saved → %s (%d FP rows)", RESULTS, len(fp_df))
    else:
        # Still write a CSV with column headers
        pd.DataFrame(columns=["artist","label","total_variance","genres","track_count",
                               "S2_bulk_proxy","S4_catalog_density","S5_genre_concentration",
                               "composite_score","threshold_regime","fp_category","review_notes"]
                    ).to_csv(RESULTS, index=False)
        log.info("Saved → %s (0 rows — no FPs at strict threshold)", RESULTS)

    # ── False negative analysis ───────────────────────────────────────────────
    ghost_proxies = df[df["label"] == 1].copy()
    fn_strict = ghost_proxies[ghost_proxies["composite_score"] < THRESHOLDS["strict"]]
    print(f"\nFalse Negatives at strict threshold: {len(fn_strict)} / {len(ghost_proxies)}")
    if len(fn_strict) > 0:
        print("  (Ghost-proxies missed — these are low-variance Kaggle artists scored < 0.983)")
        print(fn_strict[["artist","total_variance","S2_bulk_proxy","composite_score"]]
              .sort_values("composite_score").head(10).to_string(index=False))

    # ── Rate summary ──────────────────────────────────────────────────────────
    total_org = len(organics)
    fp_rate_strict = len(strict_fp) / total_org
    fp_rate_mod    = (len(strict_fp) + len(mod_fp)) / total_org
    fp_rate_lenient = (len(strict_fp) + len(mod_fp) + len(lenient_fp)) / total_org
    print(f"\nFalse Positive Rates:")
    print(f"  Strict   (τ={THRESHOLDS['strict']}): FPR={fp_rate_strict:.4f} ({len(strict_fp)}/{total_org})")
    print(f"  Moderate (τ={THRESHOLDS['moderate']}): FPR={fp_rate_mod:.4f} ({len(strict_fp)+len(mod_fp)}/{total_org})")
    print(f"  Lenient  (S2≥0.800): FPR={fp_rate_lenient:.4f} ({len(strict_fp)+len(mod_fp)+len(lenient_fp)}/{total_org})")

    print("\n⚠ CAVEAT: FP rates computed against Kaggle organic proxy labels.")
    print("  Real-world FPR may differ — library composers and single-genre")
    print("  specialists are under-represented in the Kaggle 'organic' pool.")

    # ── Write limitations.md ──────────────────────────────────────────────────
    write_limitations(
        fp_df=fp_df,
        total_organic=total_org,
        strict_fp_count=len(strict_fp),
        mod_fp_count=len(mod_fp),
        lenient_fp_count=len(lenient_fp),
        fp_categories=fp_df["fp_category"].value_counts().to_dict() if len(fp_df) > 0 else {},
    )


def write_limitations(
    fp_df: pd.DataFrame,
    total_organic: int,
    strict_fp_count: int,
    mod_fp_count: int,
    lenient_fp_count: int,
    fp_categories: dict,
) -> None:
    """Write writing/limitations.md from analysis results."""

    # Build category summary text
    cat_lines = ""
    if fp_categories:
        for cat, n in sorted(fp_categories.items(), key=lambda x: -x[1]):
            if cat == "LIBRARY_COMPOSER":
                cat_lines += f"- **Library / stock-music composers** (n={n}): Artists producing sync-licensed or background music intentionally maintain uniform sonic identity to satisfy client briefs. Examples: Two Steps from Hell, Audiomachine, Epidemic Sound-distributed composers. These artists exhibit very low audio variance by design, not by fraud.\n"
            elif cat == "GENRE_SPECIALIST":
                cat_lines += f"- **Genre specialists** (n={n}): Niche artists with deliberate single-genre focus — minimalist pianists (Ludovico Einaudi), neoclassical composers (Max Richter), or IDM artists (The Black Dog) — score high on S5 (genre concentration) and S2 (uniform audio). They are organically releasing within a narrow aesthetic range.\n"
            elif cat == "PROLIFIC_REAL":
                cat_lines += f"- **Prolific real artists** (n={n}): Artists with catalogs exceeding 200 tracks who trigger S4 (catalog density), but whose per-track audio features are variable (high S1 variance). These are misclassified when catalog size is used as a proxy for suspicion without controlling for career length.\n"
            elif cat == "AGGREGATOR_USER":
                cat_lines += f"- **Aggregator users** (n={n}): Independent artists who release 100% of their catalog through a single distributor (DistroKid, CD Baby) score HHI=1.0, identical to ghost artists using a single CUSTOM_REGISTRANT. HHI alone cannot distinguish AGGREGATOR from ghost.\n"
    if not cat_lines:
        cat_lines = "- No false positives identified at the strict operating threshold (composite ≥ 0.983) on the proxy validation set.\n"

    fp_rate_strict = strict_fp_count / max(total_organic, 1)
    fp_rate_lenient = (strict_fp_count + mod_fp_count + lenient_fp_count) / max(total_organic, 1)

    content = f"""# GhostTrack: Limitations and False Positive Analysis

*Generated by scripts/14_false_positive_analysis.py from Kaggle proxy validation set.*

---

## 1. Genre Confound (Mitigated, Not Eliminated)

The most fundamental challenge in ghost-artist detection is that ghost artists cluster in a small set of streaming-optimized genres: ambient, sleep, meditation, new-age, and classical. These genres also attract legitimate artists who maintain intentionally low audio variance — a necessary creative choice, not an indicator of fraud.

**Mitigation applied**: Script `04_regenerate_fig1.py` controls for genre by restricting both ghost and organic groups to ambient/relaxation genres. The audio variance gap survives genre-matching (Cohen's d = −1.45 to −2.08), but the effect size is smaller than in uncontrolled comparisons.

**Residual confound**: The Kaggle dataset represents popular tracks rather than ghost-artist niches. Confirmed ghost artists (Relaxing White Noise, Meditation Relax Club, Calmo) do not appear in the Kaggle 114K sample. All ghost "positive" labels in the training set are *low-variance proxy* labels — legitimate Kaggle artists with total_variance < 0.010 — not confirmed fraudsters. Any performance metrics must be interpreted with this in mind.

---

## 2. Ground Truth Limitations

**Only 3 confirmed ghost artists** have verified Spotify IDs, ISRC data, and DOJ indictment evidence (Michael Smith case, September 2024). The remaining 97 ghost artists in `data/ground_truth/ghost_artists.csv` are drawn from:

- **Dagens Nyheter investigation (2024)** — Swedish investigative journalism; Johan Röhr's Firefly Entertainment network of 656+ pseudonyms is well-documented but adjudication is ongoing
- **Kaggle low-variance artists** — low audio variance is a *necessary* but not *sufficient* condition for ghost artist status
- **Community research** — varying confidence levels

**Consequence**: The 5-fold cross-validation AUC of 1.000 does not measure the ability to detect ghost artists — it measures the ability to classify Kaggle artists by their audio variance level, which is tautological given the feature engineering. True held-out performance on real ghost artists is unknown.

**Confidence breakdown** (from ground truth CSV):
- High confidence: 7 artists (DOJ indictment or multiple independent sources)
- Medium confidence: 39 artists (single investigative source)
- Low confidence: 54 artists (variance-based proxy only)

---

## 3. False Positive Analysis

At three operating thresholds, the following false positive rates were observed on the Kaggle organic proxy set (N={total_organic} artists):

| Threshold | FPR | Count |
|---|---|---|
| Strict (composite ≥ 0.983) | {fp_rate_strict:.4f} | {strict_fp_count}/{total_organic} |
| Moderate (composite ≥ 0.500) | {(strict_fp_count + mod_fp_count)/max(total_organic,1):.4f} | {strict_fp_count + mod_fp_count}/{total_organic} |
| Lenient (S2 ≥ 0.800) | {fp_rate_lenient:.4f} | {strict_fp_count + mod_fp_count + lenient_fp_count}/{total_organic} |

**False positive categories identified** (across all threshold regimes):

{cat_lines}

**Key finding**: At the strict threshold (τ = 0.983), the composite score produces {strict_fp_count} false positives on the proxy dataset. However, this near-perfect separation is an artifact of the training procedure — ghost-proxy labels are defined by the same low-variance criterion that S2 measures. Real-world FPR will be higher, as the system has not been tested against confirmed organic artists at risk of misclassification (library composers, genre specialists).

---

## 4. Aggregator-Served Real Artists

An organic artist who releases their entire catalog through a single distributor (e.g., 100% DistroKid) will score **HHI = 1.0**, identical to a ghost artist using a single CUSTOM_REGISTRANT. The HHI signal (S6) is only interpretable when combined with the **registrant type**:

| HHI | Registrant Type | Interpretation |
|---|---|---|
| 0.8–1.0 | AGGREGATOR (DistroKid, CD Baby) | Normal independent artist — not suspicious |
| 0.8–1.0 | CUSTOM_REGISTRANT (unknown) | Ghost pattern — suspicious |
| < 0.4 | Any | Normal distribution — not suspicious |

This distinction is implemented in `scripts/07_classify_registrants.py` and `data/reference/known_aggregators.csv`. **All three confirmed ghost artists use CUSTOM_REGISTRANT prefixes; none use known aggregators.** However, this signal requires ISRC data, which is only available for artists with Spotify catalog access.

---

## 5. Geographic Bias

The confirmed ghost artists in this study are geographically concentrated:
- **German registrants** (DEPI8, DE1QW): Relaxing White Noise — 280 tracks
- **Italian registrants** (ITO10, ITLU5, ITIWE): Meditation Relax Club (172), Calmo (37)
- **Swedish registrants** (SEWA, SEWB, SEZZ, SEXX): Johan Röhr's Firefly network

This concentration reflects the specific cases documented by U.S. and European investigative sources. The detection framework may have reduced sensitivity to ghost operations using:
- U.S. or U.K. registrants (harder to distinguish from large legitimate catalogs)
- CISAC QM-block registrants (shared prefix space with legitimate aggregators)
- Legitimate aggregator prefixes deliberately chosen to blend in

**Implication**: The classifier was trained on European ghost patterns. Its transfer accuracy to North American or Asian ghost operations is unknown.

---

## 6. Temporal Scope

All release-date data covers **2020–2025**. The Michael Smith fraud was ongoing since at least 2017 (per DOJ indictment). The Kaggle 114K dataset reflects catalog popularity at time of collection, not historical upload cadence.

**Known missing signals**:
- Streaming count anomalies (Spotify streaming data not accessible via API)
- Upload velocity changes over time (requires historical data)
- Account age relative to catalog size (not available without internal Spotify data)

**Temporal HHI negative result**: Analysis in `scripts/09_regenerate_fig4.py` tested the hypothesis that ghost HHI increases over time (gradual consolidation). Finding: ghost HHI is **uniformly high from day 1**, suggesting bulk infrastructure is established before the first release. This negative result is informative about ghost-artist operational patterns.

---

## 7. Adversarial Robustness

The current framework cannot detect **adversarially obfuscated ghost artists** who deliberately:

1. **Add variance** by including a small percentage of tracks with different audio features (increasing total_variance above the 0.010 threshold)
2. **Use multiple registrants** to reduce HHI below the detection threshold (though this requires registering with multiple ISRCs, increasing operational cost)
3. **Mimic aggregator patterns** by routing through DistroKid or CD Baby rather than custom registrants
4. **Spread across genres** by releasing small batches in multiple genre categories, reducing S5

The detection framework is designed for the **current observed pattern** of ghost artists, not for adversarial adaptation. Once ghost operators become aware of specific detection signals, the framework would need to be updated.

---

## 8. Playlist Entropy (Signal S2 Component) — Negative Result

As documented in `TODO_playlists.md` and `scripts/11_regenerate_fig2.py`:

The playlist entropy component of Signal S2 was **not validated** due to Spotify API restrictions (HTTP 401 for `/playlists/{id}/tracks`). Analysis using Kaggle genre proxies found:

- ANOVA F=0.253, p=0.778 — no significant entropy difference between editorial, fan-curated, and ghost-suspect playlist groups
- All pairwise Tukey HSD comparisons: non-significant (p > 0.75)
- Cohen's d ≤ 0.27 for all pairs

**Conclusion**: Ghost artist bulk-upload is detectable at the *artist audio variance* level (S1/S2), but does not appear to create measurable entropy differences at the *playlist* level when controlling for genre. The playlist entropy signal may require real Spotify playlist data (OAuth access) to validate.

---

## Summary

The GhostTrack framework provides **proof-of-concept** detection capability demonstrated on 3 confirmed ghost artists and a Kaggle-scale proxy dataset. The headline finding — that audio variance and ISRC concentration signals clearly separate the confirmed ghost artists from organic controls — is robust. However, operational deployment would require:

1. Verified ground truth beyond 3 artists
2. Real-time Spotify API access including ISRC, playlist, and streaming data
3. Registrant-type enrichment to distinguish aggregator HHI from ghost HHI
4. Genre-stratified evaluation to measure FPR for library and specialist artists
5. Adversarial testing against ghost operators who have adapted to signal detection
"""

    out_path = WRITING / "limitations.md"
    out_path.write_text(content)
    log.info("Saved → %s", out_path)
    print(f"\nLimitations written → {out_path}")


if __name__ == "__main__":
    main()
